const val kotlinVersion: String = "1.4.10"
const val appCompat: String = "28.0.0"
const val constraintLayout: String = "1.1.3"
const val junitVersion: String = "4.+"
const val testRunnerVersion: String = "1.0.2"
const val espressoVersion: String = "3.0.2"

const val kotlinURL = "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
const val appCompatURL = "com.android.support:appcompat-v7:$appCompat"
const val constraintURL = "com.android.support.constraint:constraint-layout:$constraintLayout"
const val junitURL = "junit:junit:$junitVersion"
const val testRunnerURL = "com.android.support.test:runner:$testRunnerVersion"
const val espressoURL = "com.android.support.test.espresso:espresso-core:$espressoVersion"
